// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_irf_core_cpp
Rcpp::List compute_irf_core_cpp(const arma::mat& H_0, const arma::vec& shock, const arma::mat& xi, const arma::mat& C, const arma::mat& A, const arma::mat& G, const arma::mat& B, const arma::vec& signs, const arma::mat& psi_kurt, const arma::mat& psi_skew, const int root_type, const bool asym, const int simsamp, const int n_ahead, const int seed, const bool calc_virf, const bool calc_cirf, const bool calc_kirf, const bool calc_sirf, const bool calc_wirf);
RcppExport SEXP _bekkIRF_compute_irf_core_cpp(SEXP H_0SEXP, SEXP shockSEXP, SEXP xiSEXP, SEXP CSEXP, SEXP ASEXP, SEXP GSEXP, SEXP BSEXP, SEXP signsSEXP, SEXP psi_kurtSEXP, SEXP psi_skewSEXP, SEXP root_typeSEXP, SEXP asymSEXP, SEXP simsampSEXP, SEXP n_aheadSEXP, SEXP seedSEXP, SEXP calc_virfSEXP, SEXP calc_cirfSEXP, SEXP calc_kirfSEXP, SEXP calc_sirfSEXP, SEXP calc_wirfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type H_0(H_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type shock(shockSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type signs(signsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type psi_kurt(psi_kurtSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type psi_skew(psi_skewSEXP);
    Rcpp::traits::input_parameter< const int >::type root_type(root_typeSEXP);
    Rcpp::traits::input_parameter< const bool >::type asym(asymSEXP);
    Rcpp::traits::input_parameter< const int >::type simsamp(simsampSEXP);
    Rcpp::traits::input_parameter< const int >::type n_ahead(n_aheadSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type calc_virf(calc_virfSEXP);
    Rcpp::traits::input_parameter< const bool >::type calc_cirf(calc_cirfSEXP);
    Rcpp::traits::input_parameter< const bool >::type calc_kirf(calc_kirfSEXP);
    Rcpp::traits::input_parameter< const bool >::type calc_sirf(calc_sirfSEXP);
    Rcpp::traits::input_parameter< const bool >::type calc_wirf(calc_wirfSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_irf_core_cpp(H_0, shock, xi, C, A, G, B, signs, psi_kurt, psi_skew, root_type, asym, simsamp, n_ahead, seed, calc_virf, calc_cirf, calc_kirf, calc_sirf, calc_wirf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bekkIRF_compute_irf_core_cpp", (DL_FUNC) &_bekkIRF_compute_irf_core_cpp, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_bekkIRF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
