# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_irf_core_cpp <- function(H_0, shock, xi, C, A, G, B, signs, psi_kurt, psi_skew, root_type, asym, simsamp, n_ahead, seed, calc_virf, calc_cirf, calc_kirf, calc_sirf, calc_wirf) {
    .Call(`_bekkIRF_compute_irf_core_cpp`, H_0, shock, xi, C, A, G, B, signs, psi_kurt, psi_skew, root_type, asym, simsamp, n_ahead, seed, calc_virf, calc_cirf, calc_kirf, calc_sirf, calc_wirf)
}

